---
- name: Dev tools Provisioner
  hosts: all
  gather_facts: yes
  roles:
    - common
    - dev
    - andrewrothstein.terraform
    - andrewrothstein.kubectl
    - andrewrothstein.kubernetes-helm
    - name: geerlingguy.docker
      become: yes
  post_tasks:
    - shell: echo 'Development tools are installing finish.'
  tags: configuration  
