- name: Create symlink  gitconfig/gitignore/tigrc
  file:
    src: ~/dotfiles/git/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .gitconfig
    - .gitignore_global
    - .tigrc

- name: create symlink .vim .vimrc
  file:
    src: ~/dotfiles/vim/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .vimrc
    - .vim

- name: create symlink for nvim
  file:
    src: ~/dotfiles/vim/{{ item.src }}
    dest: ~/.config/{{ item.dest }}
    state: link
    force: yes
  with_items:
    - { src: '.vim', dest: 'nvim'}

- name: search path zsh
  command: >
    which zsh
  register: which_zsh
  ignore_errors: True

#
# login shell settings, you will be ased user's password when system switches to zsh.
#

- name: grep shells
  shell: >
    cat /etc/shells | grep "{{which_zsh.stdout}}"
  register: grep_shells
  ignore_errors: True

- name: append shells
  shell: >
    echo {{which_zsh.stdout}} >> /etc/shells
  become: true
  when: grep_shells.rc != 0

- name: change login shell
  shell: >
    chsh -s {{which_zsh.stdout}}
  register: result
  until: result.rc == 0
  retries: 3

- name: check .zsh directory existing
  stat: 
    path: ~/.zsh
  register: zshdir

- name: create .zsh directory
  file: 
    name: ~/.zsh 
    state: directory
  when: not zshdir.stat.exists

- name: create symlink
  file: 
    src: ~/dotfiles/zsh/zshenv 
    dest: ~/.zshenv 
    state: link

- name: create symlink doom emacs
  file:
    src: ~/dotfiles/doom/
    dest: ~/.config/doom/
    state: link

- name: create symlink .peco
  file:
    src: ~/dotfiles/peco
    dest: ~/.peco
    state: link
